# Settings for intermittent mode
substitutions:
  intmt_dur_slow: 20min
  intmt_dur_recirculation: 100min


esphome:
  name: echangeur-air
  friendly_name: "Échangeur d'air"
  on_boot:
    - priority: -100
      then:
        - text_sensor.template.publish:
            id: intmt_text_dur_slow
            state: $intmt_dur_slow
        - text_sensor.template.publish:
            id: intmt_text_dur_recirculation
            state: $intmt_dur_recirculation


esp8266:
  restore_from_flash: true
  board: esp8285


# Enable logging
logger:


# Enable Home Assistant API.
api:
  encryption:
    key: !secret api_key


# Enable OTA firmware update.
ota:
  password: !secret admin_password


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  on_connect:
    - output.turn_on: blue_led
  on_disconnect:
    - output.turn_off: blue_led

  # Enable Access Point in case WiFi connection fails.
  ap:
    ssid: "Échangeur d'air (4CHPRO)"
    password: !secret admin_password


# Display intermitent mode duration.
text_sensor:
  - platform: template
    name: "Intermittent: durée lente"
    id: intmt_text_dur_slow

  - platform: template
    name: "Intermittent: durée re-circulation"
    id: intmt_text_dur_recirculation


# Scripts for managing intermittent mode.
script:
  - id: intmt_trigger_enable
    then:
      - script.stop: intmt_script_stopped
      - script.execute: intmt_script_slow

  - id: intmt_trigger_disable
    then:
      - script.stop: intmt_script_stopped
      - script.stop: intmt_script_slow

  - id: intmt_script_slow
    mode: single
    then:
      - switch.turn_on: switch_slow
      - delay: $intmt_dur_slow
      - script.execute: intmt_script_stopped

  - id: intmt_script_stopped
    mode: single
    then:
      - switch.turn_on: switch_recirculation
      - delay: $intmt_dur_recirculation
      - script.execute: intmt_script_slow


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Bouton R1: Vitesse lente"
    on_press:
      - switch.toggle: switch_slow

  - platform: gpio
    pin:
      number: GPIO9
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Bouton R2: Vitesse rapide"
    on_press:
      - switch.toggle: switch_fast

  - platform: gpio
    pin:
      number: GPIO10
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Bouton R3: Re-circulation"
    on_press:
      - switch.toggle: switch_recirculation

  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Bouton R4: Arrêt complet"
    on_press:
      - switch.turn_off: switch_slow
      - switch.turn_off: switch_fast
      - switch.turn_off: switch_recirculation
      - switch.turn_off: switch_intmt

  - platform: status
    name: "Status échangeur d'air"


switch:
  # Relay R1
  - platform: gpio 
    name: "Vitesse lente"
    pin: GPIO12
    id: switch_slow
    on_turn_on:
      # Only allow one operation mode.
      - switch.turn_off: switch_fast
      - switch.turn_off: switch_recirculation

  # Relay R2
  - platform: gpio
    name: "Vitesse rapide" 
    pin: GPIO5
    id: switch_fast
    on_turn_on:
      # Only allow one operation mode.
      - switch.turn_off: switch_slow
      - switch.turn_off: switch_recirculation

  # Relay R3
  - platform: gpio
    name: "Re-circulation" 
    pin: GPIO4
    id: switch_recirculation
    on_turn_on:
      # Only allow one operation mode.
      - switch.turn_off: switch_slow
      - switch.turn_off: switch_fast

  - platform: template
    name: "Intermittent"
    id: switch_intmt
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    on_turn_on:
      - script.execute: intmt_trigger_enable
    on_turn_off:
      - script.execute: intmt_trigger_disable


output:
  # Register the blue LED as a dimmable output ....
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: true

  # Register the unused relay. Relay R4 starts high at startup if not declared here.
  - platform: gpio
    id: r4
    pin: GPIO15
